version: '3'

services:
  clovis01-springboot-container:
    image: clovis01-spring-boot-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/clovis01-springboot-container
    ports:
      - "8080-8100:8080"